name: Check suggested spec

on:
  issues:
    # Details for types below can be found at:
    # https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads?actionType=edited#issues
    types:
      # Job triggered when an issue is created or re-opened
      - opened
      - reopened

      # or gets "edited" (title or body updated)
      - edited

jobs:
  check-spec:
    name: Check suggested spec
    runs-on: ubuntu-latest
    # We're only interested in "new spec" issues
    if: ${{ contains(github.event.issue.labels.*.name, 'new spec') }}
    steps:
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      # - name: Install dependencies
      #   run: npm ci

      - name: Check suggested spec
        continue-on-error: true
        run: echo "Here's my number ($NUMBER), so call me maybe" > res.md
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          NUMBER: ${{ github.event.issue.number }}

      - name: Update last comment with result (if possible)
        id: update
        run: gh issue comment "$NUMBER" --body-file res.md --edit-last
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          NUMBER: ${{ github.event.issue.number }}

      - name: Add new comment with result
        if: ${{ failure() && steps.update.conclusion == 'failure' }}
        run: gh issue comment "$NUMBER" --body-file res.md
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          NUMBER: ${{ github.event.issue.number }}
