name: Detect push due to closed PR

on:
  push:
    branches:
      - main

jobs:
  dosomething:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
