name: Test trigger on completed workflow

on:
  workflow_run:
    workflows:
      - "Test trigger on merged PR"
    types:
      - completed
  workflow_dispatch:

jobs:
  dosomething:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
