name: Test secrets exposure in matrix

on:
  pull_request: {}
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - secret: ${{ secrets.ECHIDNA_TOKEN_WEBCODECS }}
          - secret: ${{ secrets.ECHIDNA_TOKEN_REGISTRY }}

    steps:
      - uses: actions/checkout@v2

      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ECHIDNA_TOKEN: ${{ matrix.secret }}
        with:
          filename: .github/test.md