name: Test trigger on merged PR

on:
  pull_request:
    branches:
      - main
    paths:
      - 'test.txt'
    types: [closed]

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: JasonEtco/create-an-issue@v2
        with:
          filename: .github/test.md